# Generated by Django 3.0.5 on 2020-12-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200903_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
